version: "3.3"

services:
  redis:
    container_name: redis-p5
    hostname: redis
    image: redis:8.4.0
    command: --requirepass changeme --port 6767
    ports:
      - 6767:6767
    expose:
      - 6767
    volumes:
      - ./data/redis/:/data/

  postgres:
    container_name: postgres-p5
    image: postgres:17.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vGoHZjmJHwKasdJIn30CkLvJdGvlF5dR78HC
    ports:
      - 5454:5432
    expose:
      - 5454
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/:cached

  pgadmin:
    container_name: pgadmin-p5
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
      - ./data/loki:/loki

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./config/promtail.yaml:/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - 4000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - loki

  dozzle:
    image: amir20/dozzle:latest
    ports:
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock