
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.0-dev.7
 * Query Engine version: a09903a14c97c90b4fa191ca42b02ec9a7809451
 */
Prisma.prismaVersion = {
  client: "7.4.0-dev.7",
  engine: "a09903a14c97c90b4fa191ca42b02ec9a7809451"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt',
  configuration: 'configuration'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  organizationId: 'organizationId',
  isOwner: 'isOwner',
  emailVerifiedAt: 'emailVerifiedAt',
  isBlocked: 'isBlocked',
  blockedAt: 'blockedAt',
  termsAcceptedAt: 'termsAcceptedAt',
  privacyAcceptedAt: 'privacyAcceptedAt',
  ageConfirmedAt: 'ageConfirmedAt',
  legalVersion: 'legalVersion',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.OrganizationInviteScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  createdByUserId: 'createdByUserId',
  acceptedAt: 'acceptedAt',
  revokedAt: 'revokedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApiKeyScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  tokenHash: 'tokenHash',
  tokenPrefix: 'tokenPrefix',
  expiresAt: 'expiresAt',
  lastUsedAt: 'lastUsedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.DomainGroupScalarFieldEnum = {
  id: 'id',
  name: 'name',
  organizationId: 'organizationId',
  robotsPolicy: 'robotsPolicy',
  customRobotsContent: 'customRobotsContent',
  redirectDeliveryMode: 'redirectDeliveryMode',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.DomainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domainGroupId: 'domainGroupId',
  dnsStatus: 'dnsStatus',
  dnsVerifiedAt: 'dnsVerifiedAt',
  dnsLastCheckedAt: 'dnsLastCheckedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.LinkShiftSubdomainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domainGroupId: 'domainGroupId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.RedirectRuleScalarFieldEnum = {
  id: 'id',
  source: 'source',
  destination: 'destination',
  statusCode: 'statusCode',
  matchMethod: 'matchMethod',
  queryMatch: 'queryMatch',
  pathMatch: 'pathMatch',
  linkMapId: 'linkMapId',
  isBlocked: 'isBlocked',
  blockedAt: 'blockedAt',
  priority: 'priority',
  domainGroupId: 'domainGroupId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.LinkMapScalarFieldEnum = {
  id: 'id',
  name: 'name',
  domainGroupId: 'domainGroupId',
  caseSensitive: 'caseSensitive',
  queryMatch: 'queryMatch',
  fallbackDestination: 'fallbackDestination',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.LinkMapEntryScalarFieldEnum = {
  id: 'id',
  linkMapId: 'linkMapId',
  key: 'key',
  keyNormalized: 'keyNormalized',
  destination: 'destination',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.RedirectRuleHitBreakdownHourlyScalarFieldEnum = {
  ruleId: 'ruleId',
  organizationId: 'organizationId',
  bucketStart: 'bucketStart',
  fingerprint: 'fingerprint',
  requestMethod: 'requestMethod',
  requestPath: 'requestPath',
  requestQuery: 'requestQuery',
  requestUrl: 'requestUrl',
  destination: 'destination',
  linkMapKey: 'linkMapKey',
  hits: 'hits',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RedirectTestScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  domainGroupId: 'domainGroupId',
  pathWithQuery: 'pathWithQuery',
  requestData: 'requestData',
  expectedResult: 'expectedResult',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  deletedAt: 'deletedAt'
};

exports.Prisma.BillingCheckoutSessionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  plan: 'plan',
  status: 'status',
  providerCheckoutId: 'providerCheckoutId',
  providerOrderId: 'providerOrderId',
  providerSubscriptionId: 'providerSubscriptionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  completedAt: 'completedAt',
  metadata: 'metadata'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.RobotsPolicy = exports.$Enums.RobotsPolicy = {
  NONE: 'NONE',
  ALLOW_ALL: 'ALLOW_ALL',
  DISALLOW_ALL: 'DISALLOW_ALL',
  DISALLOW_BAD_BOTS: 'DISALLOW_BAD_BOTS',
  CUSTOM: 'CUSTOM'
};

exports.RedirectDeliveryMode = exports.$Enums.RedirectDeliveryMode = {
  INSTANT: 'INSTANT',
  WITH_NOTICE: 'WITH_NOTICE'
};

exports.DomainDnsStatus = exports.$Enums.DomainDnsStatus = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  FAILED: 'FAILED'
};

exports.RedirectQueryMatch = exports.$Enums.RedirectQueryMatch = {
  exact: 'exact',
  ignore: 'ignore',
  subset: 'subset'
};

exports.RedirectPathMatch = exports.$Enums.RedirectPathMatch = {
  exact: 'exact',
  prefix: 'prefix'
};

exports.HttpMethod = exports.$Enums.HttpMethod = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  DELETE: 'DELETE',
  OPTIONS: 'OPTIONS',
  HEAD: 'HEAD'
};

exports.BillingCheckoutStatus = exports.$Enums.BillingCheckoutStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELED: 'CANCELED',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED'
};

exports.Prisma.ModelName = {
  Organization: 'Organization',
  User: 'User',
  OrganizationInvite: 'OrganizationInvite',
  ApiKey: 'ApiKey',
  DomainGroup: 'DomainGroup',
  Domain: 'Domain',
  LinkShiftSubdomain: 'LinkShiftSubdomain',
  RedirectRule: 'RedirectRule',
  LinkMap: 'LinkMap',
  LinkMapEntry: 'LinkMapEntry',
  RedirectRuleHitBreakdownHourly: 'RedirectRuleHitBreakdownHourly',
  RedirectTest: 'RedirectTest',
  BillingCheckoutSession: 'BillingCheckoutSession'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
