import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const sharedDocsRoot = resolve(repoRoot, 'shared', 'docs');
const frontendRoot = resolve(repoRoot, 'frontend');
const requireFromFrontend = createRequire(resolve(frontendRoot, 'package.json'));
const { parse: parseYaml } = requireFromFrontend('yaml');

const MANIFEST_FILE = resolve(sharedDocsRoot, 'manifest.yaml');
const OPENAPI_SOURCE = resolve(
  sharedDocsRoot,
  'openapi',
  'linkshift-api-keys.openapi.yaml',
);
const OPENAPI_PUBLIC = resolve(frontendRoot, 'public', 'linkshift-api-keys.openapi.yaml');
const SITEMAP_FILE = resolve(frontendRoot, 'public', 'sitemap.xml');
const GENERATED_FILE = resolve(
  frontendRoot,
  'src',
  'app',
  'features',
  'documentation',
  'generated',
  'documentation.generated.ts',
);

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'];

function readManifestPages() {
  const manifest = parseYaml(readFileSync(MANIFEST_FILE, 'utf8'));
  const entries = manifest?.pages;

  if (!Array.isArray(entries) || entries.length === 0) {
    throw new Error('shared/docs/manifest.yaml must define a non-empty pages array');
  }

  return entries.map((entry, index) => {
    const slug = String(entry.slug ?? '').trim();
    const category = String(entry.category ?? '').trim();
    const source = String(entry.source ?? '').trim();
    const description = String(entry.description ?? '').trim();
    const route = String(entry.route ?? '').trim();

    if (!slug || !category || !source) {
      throw new Error(`Invalid manifest page at index ${index}`);
    }

    const sourcePath = resolve(sharedDocsRoot, source);
    const markdown = readFileSync(sourcePath, 'utf8').trim();

    return {
      slug,
      category,
      route,
      sourcePath: toRepoRelative(sourcePath),
      order: index + 1,
      title: extractTitle(markdown),
      description,
      markdown,
    };
  });
}

function readOpenApiSnapshot() {
  const openapiText = readFileSync(OPENAPI_SOURCE, 'utf8');
  const openapi = parseYaml(openapiText);
  const paths = openapi?.paths ?? {};
  const endpoints = [];

  for (const [path, pathItem] of Object.entries(paths)) {
    for (const method of HTTP_METHODS) {
      const operation = pathItem?.[method];
      if (!operation || typeof operation !== 'object') {
        continue;
      }

      const operationId =
        typeof operation.operationId === 'string' && operation.operationId.trim()
          ? operation.operationId.trim()
          : makeOperationId(method, path);

      endpoints.push({
        id: operationId,
        method: method.toUpperCase(),
        path,
        tag:
          Array.isArray(operation.tags) && operation.tags.length
            ? String(operation.tags[0])
            : 'General',
        summary:
          typeof operation.summary === 'string' && operation.summary.trim()
            ? operation.summary.trim()
            : `${method.toUpperCase()} ${path}`,
      });
    }
  }

  return endpoints.sort((a, b) => {
    if (a.tag !== b.tag) {
      return a.tag.localeCompare(b.tag);
    }
    if (a.path !== b.path) {
      return a.path.localeCompare(b.path);
    }
    return a.method.localeCompare(b.method);
  });
}

function extractTitle(markdown) {
  const firstHeading = markdown
    .split('\n')
    .map((line) => line.trim())
    .find((line) => line.startsWith('# '));

  if (firstHeading) {
    return firstHeading.replace('# ', '').trim();
  }

  return 'Documentation';
}

function makeOperationId(method, path) {
  const normalized = path
    .replace(/^\/+/, '')
    .replace(/\{([^}]+)\}/g, '$1')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();

  return `${method.toLowerCase()}_${normalized || 'root'}`;
}

function toRepoRelative(filePath) {
  return filePath.replace(`${repoRoot}/`, '');
}

function copyOpenApiToPublic() {
  copyFileSync(OPENAPI_SOURCE, OPENAPI_PUBLIC);
}

function generateFile() {
  const pages = readManifestPages();
  const endpointSnapshot = readOpenApiSnapshot();
  const generatedAt = new Date().toISOString();
  const generatedDate = generatedAt.slice(0, 10);

  const output =
    `/* eslint-disable */\n` +
    `// This file is auto-generated by scripts/docs-sync.mjs\n` +
    `// Generated at: ${generatedAt}\n\n` +
    `export type DocumentationPageCategory = 'meta' | 'intro' | 'guide' | 'concept';\n\n` +
    `export type DocumentationMarkdownPage = {\n` +
    `  slug: string;\n` +
    `  category: DocumentationPageCategory;\n` +
    `  route: string;\n` +
    `  sourcePath: string;\n` +
    `  order: number;\n` +
    `  title: string;\n` +
    `  description: string;\n` +
    `  markdown: string;\n` +
    `};\n\n` +
    `export type OpenApiEndpointSnapshot = {\n` +
    `  id: string;\n` +
    `  method: string;\n` +
    `  path: string;\n` +
    `  tag: string;\n` +
    `  summary: string;\n` +
    `};\n\n` +
    `export const DOCUMENTATION_MARKDOWN_PAGES: DocumentationMarkdownPage[] = ${JSON.stringify(
      pages,
      null,
      2,
    )};\n\n` +
    `export const OPENAPI_ENDPOINTS_SNAPSHOT: OpenApiEndpointSnapshot[] = ${JSON.stringify(
      endpointSnapshot,
      null,
      2,
    )};\n`;

  writeFileSync(GENERATED_FILE, output, 'utf8');
  syncSitemap(pages, endpointSnapshot, generatedDate);
  copyOpenApiToPublic();

  console.log(`Generated ${toRepoRelative(GENERATED_FILE)}`);
  console.log(`Copied OpenAPI to ${toRepoRelative(OPENAPI_PUBLIC)}`);
  console.log(`Markdown pages: ${pages.length}`);
  console.log(`Endpoint snapshot: ${endpointSnapshot.length}`);
}

function syncSitemap(pages, endpointSnapshot, generatedDate) {
  const markerStart = '<!-- docs:start -->';
  const markerEnd = '<!-- docs:end -->';
  const sitemap = readFileSync(SITEMAP_FILE, 'utf8');

  const startIndex = sitemap.indexOf(markerStart);
  const endIndex = sitemap.indexOf(markerEnd);

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    console.warn('Skipped sitemap sync: docs markers were not found');
    return;
  }

  const docsEntries = buildSitemapEntries(pages, endpointSnapshot, generatedDate).join('\n');
  const prefix = sitemap.slice(0, startIndex + markerStart.length);
  const suffix = sitemap.slice(endIndex);
  const nextSitemap = `${prefix}\n${docsEntries}\n  ${suffix}`;

  writeFileSync(SITEMAP_FILE, nextSitemap, 'utf8');
}

function buildSitemapEntries(pages, endpointSnapshot, generatedDate) {
  const markdownEntries = pages
    .filter((page) => page.route)
    .map((page) => ({
      path: page.route,
      changefreq: page.category === 'meta' ? 'daily' : 'weekly',
      priority: page.slug === 'overview' ? '0.9' : page.slug === 'reference' ? '0.85' : '0.8',
    }));

  const endpointEntries = endpointSnapshot.map((endpoint) => ({
    path: `/docs/api/${endpoint.id}`,
    changefreq: 'weekly',
    priority: '0.7',
  }));

  const entries = [...markdownEntries, ...endpointEntries];

  return entries.map((entry) =>
    [
      '  <url>',
      `    <loc>https://linkshift.app${entry.path}</loc>`,
      `    <lastmod>${generatedDate}</lastmod>`,
      `    <changefreq>${entry.changefreq}</changefreq>`,
      `    <priority>${entry.priority}</priority>`,
      '  </url>',
    ].join('\n'),
  );
}

generateFile();
